apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "68343434"
  annotations:
    github.com/project-slug: ibrt2016/terraform-azure-web-mybob220 # Change the value to your github repo which contains terraform code.
    backstage.io/techdocs-ref: dir:.
  links:
  - url: https://github.com/claranet/terraform-azurerm-vnet
    title: 'VNet Terraform Module'
    icon: github
  tags:
    - azure
    - vnet
    - brand-new-deployment
    - high-criticality
    - ticket-number-68343434
    - entity-jp
    - owner-bob---------tayara
    - mybob220
    - prod
    - created-on-2024-07-28
  title: 'Brand new Azure Reource Group and Virtal Network - Ticket #68343434' # you can give any title
  description: |
   Create brand new Azure Reource Group and Virtal Network in stack `mybob220` in `prod` environment\
   \
   **Ticket number:**  68343434\
   **Created on:**  2024-07-28\
   Details: Create Azure Virtual network and a resource group in a brand new stack mybob220, in prod environment and in us-east region\
   Action: Create a new Resource Group and a new Virtual Network`\
   Brand new deployment: Yes\
   Azure region: us-east\
   VNet address space: 10.30.0.0/16\
   VNet suffix: 001\
   Stack name: mybob220\
   Stack owner: Bob         Tayara\
   Azure subscription: web\
   Criticality: High\
   Entity: JP\
   Cost center: 03444
spec:
  type: service
  owner: user:guest
  lifecycle: experimental