name: 'Terraform Plan'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  infra_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform plan
        id: plan
        uses: dflook/terraform-plan@v1.44.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: List
        run: ls ${{ steps.plan.outputs.plan_path }}

      # - name: Terraform Init
      #   id: init
      #   run: terraform init
  
  
  
      # - name: Terraform Plan
      #   id: plan2
      #   run: terraform plan  -input=false -no-color -out=tfplann

    
      - name: Post PR comment
        uses: borchero/terraform-plan-comment@v1
        with:
          token: ${{ secrets.GH_PAT }}
          planfile: tfplann2
          working-directory: ${{ github.workspace }}